// Task aggregation — sync from GitHub issues and watch paths

import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from "fs";
import { join } from "path";
import { loadConfigSync, harnessDir, priorityProjects, preemptAutonomy, slotsCount, milestonesEnabledProjects } from "../config.ts";
import { readAllSlotJson } from "../slots/json.ts";
import { listStashes } from "../slots/preempt.ts";
import { writeTaskFile, updateFrontmatterField, addFrontmatterField, removeFrontmatterField, parseTaskFrontmatter, updateDependencyArray, readFrontmatterField } from "./markdown.ts";
import { isElaborated } from "./elaboration.ts";
import { emitEvent } from "../events.ts";
import { queueRequest } from "../queue.ts";
import { safeSyncOutput } from "../spawn.ts";

function yamlEscape(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function contentFingerprint(text: string): string {
  const normalized = text
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, "")
    .replace(/\s+/g, " ")
    .trim();

  // Use Bun's built-in hasher
  const hasher = new Bun.CryptoHasher("md5");
  hasher.update(normalized);
  return hasher.digest("hex").slice(0, 8);
}

interface GhIssue {
  number: number;
  title: string;
  url: string;
  labels: { name: string }[];
}

interface GhIssueState extends GhIssue {
  state: string;
  stateReason?: string | null;
  closedAt?: string | null;
  updatedAt?: string | null;
  milestone?: { title: string } | null;
}

async function fetchGitHubIssues(repo: string): Promise<GhIssue[]> {
  const r = safeSyncOutput(
    ["gh", "issue", "list", "-R", repo, "--state", "open", "--limit", "200", "--json", "number,title,url,labels"],
  );
  if (!r.ok) {
    console.error(`ludics: failed to fetch issues from ${repo}: ${r.stderr}`);
    return [];
  }
  try {
    return JSON.parse(r.stdout) as GhIssue[];
  } catch {
    return [];
  }
}

export async function tasksSync(): Promise<void> {
  const config = loadConfigSync();
  const harness = harnessDir();
  const yamlFile = join(harness, "tasks.yaml");

  const timestamp = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
  const lines: string[] = [
    "# Generated by ludics",
    `generated_at: "${timestamp}"`,
    "tasks:",
  ];

  // GitHub issues from projects config
  if (config.projects) {
    for (const project of config.projects) {
      if (!project.issues) continue;
      // Issue sync uses upstream_repo when present (issues live on upstream, not the fork)
      const issueRepo = project.upstream_repo || project.repo;
      const issues = await fetchGitHubIssues(issueRepo);
      const repoName = issueRepo.split("/").pop()!;

      for (const issue of issues) {
        const id = `gh-${repoName}-${issue.number}`;
        const escapedTitle = yamlEscape(issue.title);
        const labelsStr = issue.labels.map((l) => l.name).join(",");
        lines.push(`  - id: ${id}`);
        lines.push(`    title: "${escapedTitle}"`);
        lines.push(`    source: github`);
        lines.push(`    repo: ${issueRepo}`);
        lines.push(`    url: ${issue.url}`);
        lines.push(`    labels: "${yamlEscape(labelsStr)}"`);
      }
    }
  }

  // TODO: watch paths from triggers config (deferred to Phase 4 with triggers)

  writeFileSync(yamlFile, lines.join("\n") + "\n");
  console.log(`Wrote tasks to ${yamlFile}`);

  // Auto-convert to individual task files
  await tasksConvert();

  // Refresh metadata and closed/open state for existing GitHub-backed task files
  await tasksUpdate();

  // Reconcile blocked/ready status based on dependencies
  const tasksDir = join(harness, "tasks");

  // Warn about tasks missing milestone field when milestones are enabled for their project
  tasksMilestoneWarnings(tasksDir);
  tasksReconcileBlockedStatus(tasksDir);

  // Queue elaboration for new ready tasks
  tasksQueueElaborations();

  // Queue preemptions for priority project tasks
  tasksQueuePreemptions();
}

export async function tasksConvert(): Promise<void> {
  const harness = harnessDir();
  const yamlFile = join(harness, "tasks.yaml");
  const tasksDir = join(harness, "tasks");

  if (!existsSync(yamlFile)) {
    throw new Error("tasks.yaml not found (run: ludics tasks sync first)");
  }

  mkdirSync(tasksDir, { recursive: true });
  const today = new Date().toISOString().slice(0, 10);

  const content = readFileSync(yamlFile, "utf-8");
  const lines = content.split("\n");

  let count = 0;
  let currentId = "";
  let currentTitle = "";
  let currentSource = "";
  let currentUsesBrowser = false;
  let currentRepo = "";
  let currentUrl = "";
  let currentLabels = "";

  function flushCurrent(): void {
    if (!currentId) return;
    const created = writeTaskFile(
      tasksDir, currentId, currentTitle, currentSource,
      currentUsesBrowser,
      currentRepo, currentUrl, currentLabels, today,
    );
    if (created) {
      emitEvent({ event_type: "task_github_import", source: "sync", scope: "task", task: currentId, message: currentTitle });
      count++;
    }
  }

  for (const line of lines) {
    let m: RegExpMatchArray | null;

    m = line.match(/^\s*-\s*id:\s*(.+)$/);
    if (m) {
      flushCurrent();
      currentId = m[1]!.replace(/"/g, "");
      currentTitle = "";
      currentSource = "";
      currentUsesBrowser = false;
      currentRepo = "";
      currentUrl = "";
      currentLabels = "";
      continue;
    }

    m = line.match(/^\s*title:\s*"?(.+?)"?\s*$/);
    if (m) { currentTitle = m[1]!.replace(/"$/, ""); continue; }

    m = line.match(/^\s*source:\s*(.+)$/);
    if (m) { currentSource = m[1]!; continue; }

    m = line.match(/^\s*uses_browser:\s*(.+)$/);
    if (m) {
      const v = m[1]!.trim().toLowerCase();
      currentUsesBrowser = v === "true" || v === "1" || v === "yes";
      continue;
    }

    m = line.match(/^\s*repo:\s*(.+)$/);
    if (m) { currentRepo = m[1]!; continue; }

    m = line.match(/^\s*url:\s*(.+)$/);
    if (m) { currentUrl = m[1]!; continue; }

    m = line.match(/^\s*labels:\s*"?(.*?)"?\s*$/);
    if (m) { currentLabels = m[1]!.replace(/"$/, ""); continue; }

  }

  flushCurrent();
  console.log(`Created ${count} task files in ${tasksDir}`);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function formatYamlScalar(value: string | number | boolean | null): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  // Only quote strings that contain special YAML characters or could be misinterpreted
  if (/^[a-zA-Z][a-zA-Z0-9_-]*$/.test(value)) return value;
  return `"${yamlEscape(value)}"`;
}

function setFrontmatterScalar(filePath: string, field: string, value: string | number | boolean | null): boolean {
  const content = readFileSync(filePath, "utf-8");
  const rendered = formatYamlScalar(value);
  const desiredLine = `${field}: ${rendered}`;
  const pattern = new RegExp(`^${escapeRegExp(field)}:\\s*.*$`, "m");
  const existingLine = content.match(pattern)?.[0];
  if (existingLine === desiredLine) return false;
  if (existingLine) {
    updateFrontmatterField(filePath, field, rendered);
  } else {
    addFrontmatterField(filePath, field, rendered);
  }
  return true;
}

function parseRepoFromGitHubUrl(url: string | undefined): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url);
    if (parsed.hostname !== "github.com") return null;
    const parts = parsed.pathname.split("/").filter(Boolean);
    if (parts.length < 2) return null;
    return `${parts[0]}/${parts[1]}`;
  } catch {
    return null;
  }
}

function normalizeState(value: string | null | undefined): string {
  return String(value ?? "").trim().toLowerCase();
}

function normalizeStateReason(value: string | null | undefined): string {
  return normalizeState(value).replace(/-/g, "_");
}

function readTaskProjectName(tasksDir: string, taskId: string): string {
  if (!taskId) return "";
  const taskFile = join(tasksDir, `${taskId}.md`);
  if (!existsSync(taskFile)) return "";
  const taskContent = readFileSync(taskFile, "utf-8");
  return readFrontmatterField(taskContent, "project") ?? "";
}

function collectProjectsWithQueuedPreemption(tasksDir: string, queueContent: string, priProjects: string[]): Set<string> {
  const projects = new Set<string>();

  for (const stash of listStashes()) {
    const project = readTaskProjectName(tasksDir, stash.preemptingTask);
    if (project && priProjects.includes(project)) {
      projects.add(project);
    }
  }

  for (const line of queueContent.split("\n")) {
    if (!line) continue;
    try {
      const req = JSON.parse(line) as Record<string, unknown>;
      if (req.action !== "preempt") continue;
      const qTask = String(req.task ?? "");
      const project = readTaskProjectName(tasksDir, qTask);
      if (project && priProjects.includes(project)) {
        projects.add(project);
      }
    } catch {
      // skip malformed queue lines
    }
  }

  const files = readdirSync(tasksDir).filter((f: string) => f.endsWith(".md"));
  for (const file of files) {
    const content = readFileSync(join(tasksDir, file), "utf-8");
    const statusMatch = content.match(/^status:\s*(.+)$/m);
    if (!statusMatch || statusMatch[1]!.trim() !== "preempt-queued") continue;
    const project = readFrontmatterField(content, "project") ?? "";
    if (project && priProjects.includes(project)) {
      projects.add(project);
    }
  }

  return projects;
}

function closedStatusFromIssue(issue: GhIssueState): "done" | "abandoned" | null {
  const state = normalizeState(issue.state);
  if (state !== "closed") return null;
  const reason = normalizeStateReason(issue.stateReason);
  if (reason === "not_planned") return "abandoned";
  return "done";
}

function parseIssueNumberFromTaskId(taskId: string): number | null {
  const m = taskId.match(/-(\d+)$/);
  if (!m) return null;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : null;
}

function fetchGitHubIssuesAll(repo: string): Map<number, GhIssueState> {
  const result = safeSyncOutput([
    "gh", "issue", "list",
    "-R", repo,
    "--state", "all",
    "--limit", "1000",
    "--json", "number,title,url,labels,state,stateReason,closedAt,updatedAt,milestone",
  ]);

  if (!result.ok) {
    console.error(`ludics: failed to fetch issue metadata from ${repo}: ${result.stderr}`);
    return new Map<number, GhIssueState>();
  }

  let issues: GhIssueState[] = [];
  try {
    issues = JSON.parse(result.stdout) as GhIssueState[];
  } catch {
    console.error(`ludics: failed to parse issue metadata from ${repo}`);
    return new Map<number, GhIssueState>();
  }

  if (issues.length >= 1000) {
    console.error(`ludics: warning: ${repo} returned 1000 issues; results may be truncated`);
  }

  const map = new Map<number, GhIssueState>();
  for (const issue of issues) {
    map.set(issue.number, issue);
  }
  return map;
}

interface LocalTaskRecord {
  id: string;
  filePath: string;
  source: string;
  title: string;
  githubTitle?: string;
  status: string;
  url?: string;
  project: string;
  githubIssue?: number;
  mergedInto?: string;
  mergedFrom: string[];
  neighbors: Set<string>;
}

function buildDuplicateComponents(records: Map<string, LocalTaskRecord>): {
  componentByTask: Map<string, string>;
  membersByComponent: Map<string, string[]>;
} {
  const componentByTask = new Map<string, string>();
  const membersByComponent = new Map<string, string[]>();

  for (const startId of records.keys()) {
    if (componentByTask.has(startId)) continue;
    const stack = [startId];
    const members: string[] = [];
    componentByTask.set(startId, startId);

    while (stack.length > 0) {
      const current = stack.pop()!;
      members.push(current);
      const rec = records.get(current);
      if (!rec) continue;
      for (const next of rec.neighbors) {
        if (!records.has(next)) continue;
        if (componentByTask.has(next)) continue;
        componentByTask.set(next, startId);
        stack.push(next);
      }
    }

    membersByComponent.set(startId, members);
  }

  return { componentByTask, membersByComponent };
}

function inferRepoForTask(
  record: LocalTaskRecord,
  reposBySlug: Map<string, string[]>,
): string | null {
  const parsed = parseRepoFromGitHubUrl(record.url);
  if (parsed) return parsed;
  if (!record.project) return null;
  const candidates = reposBySlug.get(record.project) ?? [];
  if (candidates.length === 1) return candidates[0]!;
  return null;
}

function inferIssueNumber(record: LocalTaskRecord): number | null {
  if (typeof record.githubIssue === "number" && Number.isFinite(record.githubIssue)) {
    return record.githubIssue;
  }
  return parseIssueNumberFromTaskId(record.id);
}

function latestIso(values: Array<string | null | undefined>): string | null {
  let latest: string | null = null;
  for (const value of values) {
    if (!value) continue;
    if (!latest || value > latest) latest = value;
  }
  return latest;
}

export async function tasksUpdate(): Promise<void> {
  const harness = harnessDir();
  const tasksDir = join(harness, "tasks");
  if (!existsSync(tasksDir)) {
    throw new Error(`tasks directory not found: ${tasksDir} (run: ludics tasks sync)`);
  }

  const files = readdirSync(tasksDir).filter((f: string) => f.endsWith(".md"));
  const records = new Map<string, LocalTaskRecord>();
  for (const file of files) {
    const filePath = join(tasksDir, file);
    const content = readFileSync(filePath, "utf-8");
    let fm;
    try {
      fm = parseTaskFrontmatter(content);
    } catch {
      continue;
    }
    if (!fm.id) continue;
    records.set(fm.id, {
      id: fm.id,
      filePath,
      source: String(fm.source ?? ""),
      title: String(fm.title ?? ""),
      githubTitle: fm.github_title,
      status: String(fm.status ?? "ready"),
      url: fm.url,
      project: String(fm.project ?? ""),
      githubIssue: fm.github_issue,
      mergedInto: fm.merged_into,
      mergedFrom: fm.merged_from ?? [],
      neighbors: new Set<string>(),
    });
  }

  for (const rec of records.values()) {
    if (rec.mergedInto && records.has(rec.mergedInto)) {
      rec.neighbors.add(rec.mergedInto);
      records.get(rec.mergedInto)!.neighbors.add(rec.id);
    }
    for (const linkedId of rec.mergedFrom) {
      if (!records.has(linkedId)) continue;
      rec.neighbors.add(linkedId);
      records.get(linkedId)!.neighbors.add(rec.id);
    }
  }

  const githubRecords = Array.from(records.values()).filter((rec) => rec.source === "github" || rec.id.startsWith("gh-"));
  if (githubRecords.length === 0) {
    console.log("No GitHub-backed task files found");
    return;
  }

  const config = loadConfigSync();
  const reposBySlug = new Map<string, string[]>();
  for (const project of (config.projects ?? [])) {
    // Issue operations target upstream_repo when present (issues live upstream, not on fork)
    const issueRepo = project.upstream_repo || project.repo;
    const slug = issueRepo.split("/").pop() ?? "";
    if (!slug) continue;
    const existing = reposBySlug.get(slug) ?? [];
    existing.push(issueRepo);
    reposBySlug.set(slug, existing);
  }

  const issueNumbersByRepo = new Map<string, Set<number>>();
  let unresolvedRepo = 0;
  let unresolvedIssue = 0;
  for (const rec of githubRecords) {
    const repo = inferRepoForTask(rec, reposBySlug);
    if (!repo) {
      unresolvedRepo++;
      console.error(`ludics: could not infer repo for ${rec.id}; skipping`);
      continue;
    }
    const issueNumber = inferIssueNumber(rec);
    if (!issueNumber) {
      unresolvedIssue++;
      console.error(`ludics: could not infer issue number for ${rec.id}; skipping`);
      continue;
    }
    const bucket = issueNumbersByRepo.get(repo) ?? new Set<number>();
    bucket.add(issueNumber);
    issueNumbersByRepo.set(repo, bucket);
  }

  const issuesByRepo = new Map<string, Map<number, GhIssueState>>();
  for (const repo of issueNumbersByRepo.keys()) {
    issuesByRepo.set(repo, fetchGitHubIssuesAll(repo));
  }

  const { componentByTask, membersByComponent } = buildDuplicateComponents(records);
  const closureIntents = new Map<string, Array<{ status: "done" | "abandoned"; closedAt: string | null }>>();

  let metadataUpdates = 0;
  let stateClosures = 0;
  let titleSynced = 0;
  let titlePreserved = 0;
  let matchedIssues = 0;
  let missingOnGitHub = 0;
  const touchedTasks = new Set<string>();

  for (const rec of githubRecords) {
    const repo = inferRepoForTask(rec, reposBySlug);
    const issueNumber = inferIssueNumber(rec);
    if (!repo || !issueNumber) continue;

    const issue = issuesByRepo.get(repo)?.get(issueNumber);
    if (!issue) {
      missingOnGitHub++;
      console.error(`ludics: issue not found in ${repo}: #${issueNumber} (${rec.id})`);
      continue;
    }
    matchedIssues++;

    const labelsCsv = issue.labels.map((label) => label.name).join(",");
    const state = normalizeState(issue.state);
    const stateReason = normalizeStateReason(issue.stateReason);

    const previousRemoteTitle = rec.githubTitle;
    const localTitle = rec.title;
    const remoteTitle = issue.title;
    const canAutoSyncTitle =
      typeof previousRemoteTitle === "string" &&
      localTitle === previousRemoteTitle;

    let titleChanged = false;
    if (canAutoSyncTitle) {
      titleChanged = setFrontmatterScalar(rec.filePath, "title", remoteTitle);
      if (titleChanged) {
        titleSynced++;
        touchedTasks.add(rec.id);
      }
    } else if (localTitle !== remoteTitle) {
      // Local title diverged from remote snapshot; preserve local intent.
      titlePreserved++;
    }

    const milestoneTitle = issue.milestone?.title ?? null;

    // Handle milestone sync: set when GitHub has one, remove when GitHub cleared it.
    // Only remove if the field currently exists in the file (avoid adding null lines).
    let milestoneChanged = false;
    if (milestoneTitle !== null) {
      milestoneChanged = setFrontmatterScalar(rec.filePath, "milestone", milestoneTitle);
    } else {
      // GitHub has no milestone — remove stale local field if present
      const fileContent = readFileSync(rec.filePath, "utf-8");
      if (/^milestone:/m.test(fileContent)) {
        removeFrontmatterField(rec.filePath, "milestone");
        milestoneChanged = true;
      }
    }

    const updates = [
      setFrontmatterScalar(rec.filePath, "github_title", remoteTitle),
      setFrontmatterScalar(rec.filePath, "url", issue.url),
      setFrontmatterScalar(rec.filePath, "github_repo", repo),
      setFrontmatterScalar(rec.filePath, "github_issue", issue.number),
      setFrontmatterScalar(rec.filePath, "github_labels", labelsCsv),
      setFrontmatterScalar(rec.filePath, "github_state", state || "open"),
      setFrontmatterScalar(rec.filePath, "github_state_reason", stateReason || null),
      setFrontmatterScalar(rec.filePath, "github_updated_at", issue.updatedAt ?? null),
      setFrontmatterScalar(rec.filePath, "github_closed_at", issue.closedAt ?? null),
      milestoneChanged,
    ];

    const metadataChanged = updates.filter(Boolean).length;
    if (metadataChanged > 0) {
      metadataUpdates += metadataChanged;
      touchedTasks.add(rec.id);
    }

    const closedStatus = closedStatusFromIssue(issue);
    if (!closedStatus) continue;
    const componentId = componentByTask.get(rec.id) ?? rec.id;
    const intents = closureIntents.get(componentId) ?? [];
    intents.push({ status: closedStatus, closedAt: issue.closedAt ?? null });
    closureIntents.set(componentId, intents);
  }

  for (const [componentId, intents] of closureIntents.entries()) {
    const closureStatus: "done" | "abandoned" = intents.some((item) => item.status === "abandoned")
      ? "abandoned"
      : "done";
    const completedAt = latestIso(intents.map((item) => item.closedAt))
      ?? new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
    const members = membersByComponent.get(componentId) ?? [componentId];

    for (const taskId of members) {
      const rec = records.get(taskId);
      if (!rec) continue;
      if (rec.status === "merged") continue;

      let changed = false;
      if (!["done", "abandoned"].includes(rec.status)) {
        if (setFrontmatterScalar(rec.filePath, "status", closureStatus)) {
          emitEvent({ event_type: "task_status_change", source: "sync", scope: "task", task: taskId, status: closureStatus, message: `GitHub issue closed (${closureStatus})` });
          stateClosures++;
          changed = true;
        }
      }
      if (setFrontmatterScalar(rec.filePath, "completed", completedAt)) {
        changed = true;
      }
      if (changed) touchedTasks.add(taskId);
    }
  }

  // --- Reverse sync: close GitHub issues for locally completed tasks ---
  let issuesClosed = 0;
  for (const rec of githubRecords) {
    if (rec.status !== "done" && rec.status !== "abandoned") continue;

    const repo = inferRepoForTask(rec, reposBySlug);
    const issueNumber = inferIssueNumber(rec);
    if (!repo || !issueNumber) continue;

    const issue = issuesByRepo.get(repo)?.get(issueNumber);
    if (!issue) continue;

    const ghState = normalizeState(issue.state);
    if (ghState !== "open") continue; // already closed on GitHub

    const ghArgs = ["gh", "issue", "close", "-R", repo, String(issueNumber)];
    if (rec.status === "abandoned") {
      ghArgs.push("--reason", "not planned");
    }

    const closeResult = safeSyncOutput(ghArgs);
    if (closeResult.ok) {
      emitEvent({ event_type: "task_github_reverse_close", source: "sync", scope: "task", task: rec.id, status: rec.status, message: `closed ${repo}#${issueNumber} as ${rec.status}` });
      issuesClosed++;
      console.error(`ludics: closed ${repo}#${issueNumber} as ${rec.status}`);
    } else {
      console.error(`ludics: failed to close ${repo}#${issueNumber}: ${closeResult.stderr}`);
    }
  }

  console.log(
    `Updated ${touchedTasks.size} task(s): ${metadataUpdates} metadata field change(s), ${titleSynced} title sync(s), ${stateClosures} closed-state status change(s), ${issuesClosed} GitHub issue(s) closed`,
  );
  console.log(
    `Preserved ${titlePreserved} local title override(s)`,
  );
  console.log(
    `Matched ${matchedIssues}/${githubRecords.length} GitHub-backed task(s); unresolved repo=${unresolvedRepo}, unresolved issue=${unresolvedIssue}, missing on GitHub=${missingOnGitHub}`,
  );
}

/**
 * Heal blocked_by/blocks links: remove done/abandoned tasks from blocked_by,
 * and ensure each blocked_by reference has a matching blocks backlink.
 */
function healBlockedByLinks(tasksDir: string): void {
  const files = readdirSync(tasksDir).filter((f: string) => f.endsWith(".md"));

  // Build id -> { status, filePath, fm } map
  const taskMap = new Map<string, { status: string; filePath: string; fm: ReturnType<typeof parseTaskFrontmatter> }>();
  for (const f of files) {
    const filePath = join(tasksDir, f);
    const content = readFileSync(filePath, "utf-8");
    let fm;
    try { fm = parseTaskFrontmatter(content); } catch { continue; }
    taskMap.set(fm.id, { status: fm.status ?? "ready", filePath, fm });
  }

  const terminalStatuses = new Set(["done", "abandoned"]);
  let healed = 0;

  for (const [taskId, entry] of taskMap) {
    const blockedBy = entry.fm.dependencies?.blocked_by ?? [];
    if (blockedBy.length === 0) continue;

    // Ensure each blocker has a blocks backlink (preserving full graph in blocks)
    for (const depId of blockedBy) {
      const dep = taskMap.get(depId);
      if (!dep) continue;
      const blocks = dep.fm.dependencies?.blocks ?? [];
      if (!blocks.includes(taskId)) {
        updateDependencyArray(dep.filePath, "blocks", [...blocks, taskId]);
        healed++;
      }
    }

    // Remove done/abandoned tasks from blocked_by (keep unknown refs — may be external)
    const pruned = blockedBy.filter((depId) => {
      const dep = taskMap.get(depId);
      return dep == null || !terminalStatuses.has(dep.status);
    });

    if (pruned.length !== blockedBy.length) {
      updateDependencyArray(entry.filePath, "blocked_by", pruned);
      healed++;
    }
  }

  if (healed > 0) {
    console.error(`ludics: healed ${healed} blocked_by/blocks link(s)`);
  }
}

function tasksReconcileBlockedStatus(tasksDir: string): void {
  // Heal stale blocked_by links before checking status
  healBlockedByLinks(tasksDir);

  const files = readdirSync(tasksDir).filter((f: string) => f.endsWith(".md"));
  let reconciled = 0;

  for (const f of files) {
    const filePath = join(tasksDir, f);
    const content = readFileSync(filePath, "utf-8");
    let fm;
    try {
      fm = parseTaskFrontmatter(content);
    } catch { continue; }

    const status = fm.status ?? "ready";
    const blockedBy = fm.dependencies?.blocked_by ?? [];

    // Skip terminal and active statuses
    if (["done", "abandoned", "merged", "in-progress", "deferred", "preempt-queued", "preempted"].includes(status)) continue;

    if (blockedBy.length > 0 && status === "ready") {
      if (setFrontmatterScalar(filePath, "status", "blocked")) {
        emitEvent({ event_type: "task_status_change", source: "sync", scope: "task", task: fm.id, status: "blocked", message: `blocked by: ${blockedBy.join(", ")}` });
        reconciled++;
      }
    } else if (blockedBy.length === 0 && status === "blocked") {
      if (setFrontmatterScalar(filePath, "status", "ready")) {
        emitEvent({ event_type: "task_status_change", source: "sync", scope: "task", task: fm.id, status: "ready", message: "all blockers resolved" });
        reconciled++;
      }
    }
  }

  if (reconciled > 0) {
    console.error(`ludics: reconciled status for ${reconciled} task(s)`);
  }
}

function tasksMilestoneWarnings(tasksDir: string): void {
  const milestonesProjects = milestonesEnabledProjects();
  if (milestonesProjects.size === 0) return;
  if (!existsSync(tasksDir)) return;

  const files = readdirSync(tasksDir).filter((f: string) => f.endsWith(".md"));
  const missing: string[] = [];

  for (const f of files) {
    const content = readFileSync(join(tasksDir, f), "utf-8");
    let fm;
    try {
      fm = parseTaskFrontmatter(content);
    } catch { continue; }

    // Only warn for active (non-terminal) tasks
    const status = fm.status ?? "ready";
    if (["done", "abandoned", "merged"].includes(status)) continue;

    if (!milestonesProjects.has(fm.project ?? "")) continue;

    if (!fm.milestone) {
      missing.push(fm.id);
    }
  }

  if (missing.length > 0) {
    console.warn(`ludics: warning: ${missing.length} task(s) missing milestone field (milestones enabled): ${missing.join(", ")}`);
  }
}

function tasksQueueElaborations(): void {
  const harness = harnessDir();
  const tasksDir = join(harness, "tasks");
  if (!existsSync(tasksDir)) return;

  const queueFile = join(harness, "mag", "queue.jsonl");
  const alreadyQueuedElaborateTasks = new Set<string>();
  if (existsSync(queueFile)) {
    for (const line of readFileSync(queueFile, "utf-8").split("\n")) {
      if (!line) continue;
      try {
        const req = JSON.parse(line) as Record<string, unknown>;
        if (req.action === "elaborate" && typeof req.task === "string") {
          alreadyQueuedElaborateTasks.add(req.task);
        }
      } catch { /* skip malformed lines */ }
    }
  }

  const needsElab = tasksNeedsElaborationList(tasksDir);
  let count = 0;

  for (const taskId of needsElab) {
    const file = join(tasksDir, `${taskId}.md`);
    if (!existsSync(file)) continue;

    const content = readFileSync(file, "utf-8");
    const statusMatch = content.match(/^status:\s*(.+)$/m);
    if (statusMatch && statusMatch[1]!.trim() !== "ready") continue;

    if (isElaborated(content)) continue;

    if (alreadyQueuedElaborateTasks.has(taskId)) continue;

    queueRequest({ action: "elaborate", task: taskId });
    emitEvent({ event_type: "task_elaborate_queued", source: "sync", scope: "task", task: taskId });
    count++;
  }

  if (count > 0) {
    console.error(`ludics: Queued ${count} task(s) for elaboration`);
  }
}

function tasksNeedsElaborationList(tasksDir: string): string[] {
  const files = readdirSync(tasksDir).filter((f: string) => f.endsWith(".md"));
  const result: string[] = [];

  for (const f of files) {
    const content = readFileSync(join(tasksDir, f), "utf-8");
    const idMatch = content.match(/^id:\s*(.+)$/m);
    if (!idMatch) continue;
    const id = idMatch[1]!.trim();

    const statusMatch = content.match(/^status:\s*(.+)$/m);
    const status = statusMatch ? statusMatch[1]!.trim() : "";
    if (["merged", "done", "abandoned", "needs-confirmation"].includes(status)) continue;

    if (!isElaborated(content)) result.push(id);
  }

  return result;
}

function tasksQueuePreemptions(): void {
  const priProjects = priorityProjects();
  if (priProjects.length === 0) return;

  const harness = harnessDir();
  const tasksDir = join(harness, "tasks");
  if (!existsSync(tasksDir)) return;

  // Check if all slots are occupied (otherwise normal flow ready path suffices)
  const slots = readAllSlotJson(slotsCount(), harness);
  let hasEmpty = false;
  for (const [, data] of slots) {
    const process = data.process.trim();
    if (!process || process === "(empty)") { hasEmpty = true; break; }
  }
  if (hasEmpty) return; // empty slot available, no need to preempt

  const queueFile = join(harness, "mag", "queue.jsonl");
  let alreadyQueued = "";
  const alreadyQueuedPreemptTasks = new Set<string>();
  if (existsSync(queueFile)) {
    alreadyQueued = readFileSync(queueFile, "utf-8");
    for (const line of alreadyQueued.split("\n")) {
      if (!line) continue;
      try {
        const req = JSON.parse(line) as Record<string, unknown>;
        if (req.action === "preempt" && typeof req.task === "string") {
          alreadyQueuedPreemptTasks.add(req.task);
        }
      } catch { /* skip malformed lines */ }
    }
  }

  // Limit active preemptions per project, not globally. A priority project already
  // occupying a normal slot should not block another project from getting one
  // preempted slot of its own.
  const projectsInFlight = collectProjectsWithQueuedPreemption(tasksDir, alreadyQueued, priProjects);

  const files = readdirSync(tasksDir).filter((f: string) => f.endsWith(".md"));
  let queued = 0;

  for (const f of files) {
    const content = readFileSync(join(tasksDir, f), "utf-8");
    const idMatch = content.match(/^id:\s*(.+)$/m);
    if (!idMatch) continue;
    const id = idMatch[1]!.trim();

    const statusMatch = content.match(/^status:\s*(.+)$/m);
    if (!statusMatch || statusMatch[1]!.trim() !== "ready") continue;

    const project = readFrontmatterField(content, "project") ?? "";
    if (!project) continue;

    if (!priProjects.includes(project)) continue;
    if (projectsInFlight.has(project)) continue; // one preemption per project at a time
    if (alreadyQueuedPreemptTasks.has(id)) continue;

    const autonomy = preemptAutonomy();
    queueRequest({ action: "preempt", task: id, autonomy });
    emitEvent({ event_type: "task_preempt_queued", source: "sync", scope: "task", task: id, message: `priority project: ${project}` });
    // Mark task immediately so subsequent syncs won't re-queue it
    // (closes the race window between queue-pop and actual slot assignment)
    updateFrontmatterField(join(tasksDir, f), "status", "preempt-queued");
    projectsInFlight.add(project); // prevent queuing another from same project in this pass
    queued++;
  }

  if (queued > 0) {
    console.error(`ludics: Queued ${queued} priority task(s) for preemption`);
  }
}

export { tasksNeedsElaborationList, tasksQueueElaborations, tasksQueuePreemptions, tasksReconcileBlockedStatus, contentFingerprint };
